info:
  app:
    name: '@project.name@'
    version: '@project.version@'
server:
  port: 8080
spring:
  datasource:
    name: PropostaDataSource
    driver-class-name: org.postgresql.Driver    
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/proposta-db}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: propostaPool
      connection-test-query: select now()
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 10000
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
# Feign

app:
  solicitation:
    url: http://localhost:9999
    path: /api/solicitacao

# actuator
management:
  endpoint:    health:      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
